service: aws-serverless-nodejs-stepfunctions

frameworkVersion: "2"

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource:
        - Ref: EmailSchedulingStateMachine
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: arn:aws:ses:#{AWS::Region}:#{AWS::AccountId}:identity/${self:custom.EMAIL_SENDER_ADDRESS}

custom:
  EMAIL_SENDER_ADDRESS: marcelo@github.com

package:
  individually: true

functions:
  ScheduleEmail:
    handler: emails/functions/schedule-email.handle
    environment:
      STATEMACHINE_ARN: ${self:resources.Outputs.EmailSchedulingStateMachine.Value}

  SendEmail:
    handler: emails/functions/send-email.handle
    environment:
      EMAIL_SENDER_ADDRESS: ${self:custom.EMAIL_SENDER_ADDRESS}

stepFunctions:
  stateMachines:
    EmailSchedulingStateMachine:
      name: EmailSchedulingStateMachine
      definition:
        Comment: "Schedules an email to be sent at a future date"
        StartAt: WaitForDueDate
        States:
          WaitForDueDate:
            Type: Wait
            TimestampPath: "$.dueDate"
            Next: SendEmail
          SendEmail:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-SendEmail"
            End: true

resources:
  Outputs:
    EmailSchedulingStateMachine:
      Description: The ARN of the EmailSchedulingStateMachine
      Value:
        Ref: EmailSchedulingStateMachine
